<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <PackageVersion Include="Avalonia" Version="11.2.3" />
        <PackageVersion Include="Avalonia.Diagnostics" Version="11.2.3" />
        <PackageVersion Include="Avalonia.Desktop" Version="11.2.3" />
        <PackageVersion Include="Avalonia.Fonts.Inter" Version="11.2.3" />
        <PackageVersion Include="Avalonia.ReactiveUI" Version="11.2.3" />
        <PackageVersion Include="Avalonia.Themes.Fluent" Version="11.2.3" />
        <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
        <PackageVersion Include="Microsoft.Extensions.Http" Version="9.0.2" />
        <PackageVersion Include="Microsoft.Extensions.Logging" Version="9.0.2" />
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.2" />
        <PackageVersion Include="ReactiveUI.Fody" Version="19.5.41" />
        <PackageVersion Include="ReactiveUI.Validation" Version="4.1.1" />
        <PackageVersion Include="Serilog" Version="4.2.0" />
        <PackageVersion Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageVersion Include="Serilog.Extensions.Logging" Version="9.0.0" />
        <PackageVersion Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageVersion Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageVersion Include="Serilog.Sinks.File" Version="6.0.0" />
    </ItemGroup>
</Project>
