<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <OutputType>Library</OutputType>

        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Fonts\*.ttf" />
        <AvaloniaResource Include="Fonts\*.axaml" />
        <AvaloniaResource Include="Styles\*.axaml" />
        <AvaloniaResource Include="Index.axaml" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
    </ItemGroup>
</Project>
