<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>Library</OutputType>

        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <UserSecretsId>604bcea0-0583-4597-9afc-fbf849a6fb90</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <None Include="FodyWeavers.xsd">
            <DependentUpon>FodyWeavers.xml</DependentUpon>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Diagnostics">
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="Avalonia.ReactiveUI" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Http" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="ReactiveUI.Fody" />
        <PackageReference Include="ReactiveUI.Validation" />
        <PackageReference Include="Serilog.Extensions.Logging" />
        <PackageReference Include="Serilog.Sinks.Debug" />
        <PackageReference Include="Serilog.Sinks.File" />
        <PackageReference Include="Microsoft.Extensions.Configuration" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging" />
        <ProjectReference Include="..\ImeSense.Launchers.Belarus.Core\ImeSense.Launchers.Belarus.Core.csproj" />
        <ProjectReference Include="..\ImeSense.Launchers.Belarus.Themes.Avalonia\ImeSense.Launchers.Belarus.Themes.Avalonia.csproj" />
    </ItemGroup>
</Project>
