<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <None Include="FodyWeavers.xsd">
            <DependentUpon>FodyWeavers.xml</DependentUpon>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.1.3" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.1.3" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.1.3" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.1.3" Condition="'$(Configuration)' == 'Debug'" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.1.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
        <PackageReference Include="ReactiveUI.Fody" Version="19.5.41" />
        <PackageReference Include="ReactiveUI.Validation" Version="4.0.9" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
        <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.Launchers.Belarus.Core\ImeSense.Launchers.Belarus.Core.csproj" />
        <ProjectReference Include="..\ImeSense.Launchers.Belarus.Themes.Avalonia\ImeSense.Launchers.Belarus.Themes.Avalonia.csproj" />
    </ItemGroup>
</Project>
