<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <OutputType>WinExe</OutputType>

        <InvariantGlobalization>false</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <TrimmableAssembly Include="ImeSense.Launchers.Belarus.Themes.Avalonia" />
        <TrimmerRootDescriptor Include="TrimmerRoots.xml" />
    </ItemGroup>

    <PropertyGroup>
        <ApplicationIcon>..\ImeSense.Launchers.Belarus\Assets\Icons\stalker_cs.ico</ApplicationIcon>
        <AssemblyName>SBLauncher</AssemblyName>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <PublishAot>true</PublishAot>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Desktop" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImeSense.Launchers.Belarus\ImeSense.Launchers.Belarus.csproj" />
    </ItemGroup>
</Project>
